version: '3'
services:    
  database:
    container_name: database
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  cdn:
    build: ./cdn
    container_name: cdn
    restart: on-failure
    volumes:
      - ./cdn:/cdn
    ports:
      - "4000:4000"
    command: gunicorn app:app --bind=0.0.0.0:4000
    depends_on:
      - database

  server:
    build: ./server
    container_name: backend
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@database:5432/postgres
      - CDN_URL=https://cdn:4000
      - JWT_SECRET_KEY=some_secret_key
    restart: on-failure
    volumes:
      - ./server:/server
      - ./cdn:/cdn
    ports:
      - "5000:5000"
    command: gunicorn app:app --bind=0.0.0.0:5000
    depends_on:
      - cdn

  client:
    build: 
      context: ./client
      args:
        SERVER_URL: "ne ebu chto"
    container_name: client
    restart: on-failure
    ports:
      - "3000:3000"
    command: serve -s build
    depends_on:
      - server

volumes:
  pgdata: {}