version: '3.9'
services:
  server:
    container_name: backend
    build: ./server
    ports:
      - "5000:5000"
    restart: on-failure
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@fix_it_now_db:5432/postgres
      - JWT_SECRET_KEY=ijcicjh;IHW;OIH:oihaoih
    volumes:
      - ./server:/server
    command: flask run --host=0.0.0.0 --port=5000
    depends_on:
      - fix_it_now_db
  
  fix_it_now_db:
    container_name: fix_it_now_db
    image: postgres:12
    restart: "on-failure"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  client:
    container_name: client
    build: 
      context: ./client
      args:
        REACT_APP_SERVER_URL: https://friendly-space-winner-wrr746j5q5gx39q5g-5000.app.github.dev/api/
    restart: on-failure
    ports:
      - "3000:3000"
    command: serve -s build
    depends_on:
      - server


volumes:
  pgdata: {}